### ISSUE TITLE
No usar PX como medida en el css

### ISSUE THREAD

**Issue by fernando1989mg** [jisdote/excursion#1]
no usar PX en tu css y usar em o rem 

:p

**Comment by jisdote** [comment]
Este es un ejercicio para Codecademy en el que se desarrolla una página sencilla en base a un [mockup de diseño](https://content.codecademy.com/programs/freelance-one/excursion/mocks/excursion.png) y [redline](https://content.codecademy.com/programs/freelance-one/excursion/mocks/excursion_redline.png); este último entrega especificaciones de estilos. Con la intención de preservar las instrucciones, y así aprobar esta tarea, se desarrolló con el CSS que había sido indicado.

Cerrando el ticket 😎
